### ISSUE TITLE
Texture Requests

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#18]
I thought it would make sense to keep track of what textures we could use, in order of importance:
 _emphasized_ = with tool materials (wood, stone, iron, gold, diamond)

Javelin
Musket
_Knife_
_Musket with Bajonet (Knife)_
Blunderbuss
Blowgun + (different?) Darts

**Comment by Squeekblach** [comment]
![holy cross](https://cloud.githubusercontent.com/assets/16748858/12380858/c42ce3a0-bd4a-11e5-98a0-3cb26bcb0d33.png)
![wooden holy cross](https://cloud.githubusercontent.com/assets/16748858/12380859/c6433248-bd4a-11e5-9c3b-5b87f1ab4a90.png)
![blowgun](https://cloud.githubusercontent.com/assets/16748858/12380945/8d75ca4a-bd4d-11e5-9fa7-236af0f0ba2f.png)
![diamonddagger](https://cloud.githubusercontent.com/assets/16748858/12381037/b72a8748-bd4f-11e5-880a-eb2fa51eb079.png)
![irondagger](https://cloud.githubusercontent.com/assets/16748858/12381039/bb4ba780-bd4f-11e5-8e89-6c9a2c48e486.png)
![golddagger](https://cloud.githubusercontent.com/assets/16748858/12381040/bebf15b4-bd4f-11e5-9bfe-d369e90833f1.png)
![stonedagger](https://cloud.githubusercontent.com/assets/16748858/12381043/c643a890-bd4f-11e5-8a5f-03bd4156f75c.png)
![woodendagger](https://cloud.githubusercontent.com/assets/16748858/12381045/c8a6b258-bd4f-11e5-8d0c-4b7e79645d0e.png)
![hungerdart](https://cloud.githubusercontent.com/assets/16748858/12381189/028233aa-bd53-11e5-9d77-b9313249c2ac.png)
![normaldart](https://cloud.githubusercontent.com/assets/16748858/12381190/0a4e1824-bd53-11e5-8995-56d9455c36e4.png)
![poisondart](https://cloud.githubusercontent.com/assets/16748858/12381191/0debc648-bd53-11e5-9ed2-7d058b5d5a6d.png)
![slownessdart](https://cloud.githubusercontent.com/assets/16748858/12381192/103d1b5e-bd53-11e5-923f-be01d025e935.png)
![strongpoisondart](https://cloud.githubusercontent.com/assets/16748858/12381193/13c0596c-bd53-11e5-8172-513b4170e737.png)
![witherdart](https://cloud.githubusercontent.com/assets/16748858/12381194/1638ffc8-bd53-11e5-98b6-935c3b5d8859.png)

**Comment by ThexXTURBOXx** [comment]
Looks cool! It'd be very cool, if you could provide those in copper, tin and silver, too :D (I am working on the OreDictionary-Things right now ^^)

**Comment by TheOnlySilverClaw** [comment]
Nananana, let him handle the list. Suncore can do the material stuff. :P

**Comment by ThexXTURBOXx** [comment]
Ok, then forget my comment :P

**Comment by Sunconure11** [comment]
I'll work on tin and silver tomorrow. I just managed to get my sleep on track, and there are a few other things I need to work on.

**Comment by Squeekblach** [comment]
![musket](https://cloud.githubusercontent.com/assets/16748858/12406972/4d8aaa44-be20-11e5-9dbf-1fbf60472ee6.png)
![musketbarrel](https://cloud.githubusercontent.com/assets/16748858/12406973/5138de18-be20-11e5-8bbf-cb9bb665564e.png)
![musketstock](https://cloud.githubusercontent.com/assets/16748858/12406975/5355dfde-be20-11e5-8ab2-9cb64096ab7f.png)
![blunderbussbarrel](https://cloud.githubusercontent.com/assets/16748858/12409028/5342de20-be34-11e5-8d43-f268ec52ea88.png)
![blunderbussshot](https://cloud.githubusercontent.com/assets/16748858/12406979/59e0312e-be20-11e5-8e50-81ba7928dc87.png)
![musketround](https://cloud.githubusercontent.com/assets/16748858/12406981/5cfbce86-be20-11e5-8932-303afe6b2db6.png)
![musketironbayonet](https://cloud.githubusercontent.com/assets/16748858/12406983/60050e8a-be20-11e5-8003-d251c6fa17d7.png)
![musketstonebayonet](https://cloud.githubusercontent.com/assets/16748858/12406985/628e4bd0-be20-11e5-957a-36d1e84316c0.png)
![musketwoodbayonet](https://cloud.githubusercontent.com/assets/16748858/12406987/65968338-be20-11e5-9753-190cc56e16a6.png)
![musketdiamondbayonet](https://cloud.githubusercontent.com/assets/16748858/12406988/686f3a32-be20-11e5-8db6-b089009be0b3.png)
![musketgoldbayonet](https://cloud.githubusercontent.com/assets/16748858/12406989/6a11e3f8-be20-11e5-8854-7e40ff6b786a.png)
![blunderbussshort](https://cloud.githubusercontent.com/assets/16748858/12408020/802175f0-be2a-11e5-8cd2-356a3e5a42ee.png)
![javelin](https://cloud.githubusercontent.com/assets/16748858/12407007/8c1a49b8-be20-11e5-84f0-83748491f852.png)

And that should be everything on this list.

**Comment by TheOnlySilverClaw** [comment]
I did not really recognize the Javelin (looks more like a shovel on first site o.O ), but the rest look great. Thanks you!

**Comment by Squeekblach** [comment]
Yeah I can see that...
![newjavelin](https://cloud.githubusercontent.com/assets/16748858/12424064/7bbfbed2-be9c-11e5-9b0d-1534e8f314b8.png)
I tried to base this one more off of Olympic javelins. Tell me what you think.

**Comment by TheOnlySilverClaw** [comment]
First of all, I think it does not make sense to keep the Javelin at 16 Pixels, while all other pole weapons are 32.
16 Pixel just does not look good for items longer than a sword.

Besides, MAYBE we could go into the Roman direction (or maybe make that a stronger version?)
https://duckduckgo.com/?t=lm&q=pilum&iax=1&ia=images

If we stay 'primitive', maybe make the tip look more like a flint, since that was in the crafting recipe, maybe just a little thinner.

**Comment by Squeekblach** [comment]
Okay, I made the tip look like flint and it's 32x32 now.
![javelin1](https://cloud.githubusercontent.com/assets/16748858/12435190/e0bd28e6-bed9-11e5-974e-69d00956e667.png)
![javelin2](https://cloud.githubusercontent.com/assets/16748858/12435192/e381ca28-bed9-11e5-9c01-8dbcdfbf2eec.png)
![javelin3](https://cloud.githubusercontent.com/assets/16748858/12435194/e61b329c-bed9-11e5-98bf-e6c87deee1cb.png)
One looks the most refined and three looks the most primitive. Take your pick.

**Comment by TheOnlySilverClaw** [comment]
Thanks.
It is too much to ask for a grip, once we decided on one?^^

**Comment by Squeekblach** [comment]
Not at all, I enjoy doing this. What kind of grip? Like the wrap around the handle of the battleaxe? Or something else?

**Comment by TheOnlySilverClaw** [comment]
Yeah, something like that. I'm trying to recall what the javelins in our sports classes looked like...I think it's more or less in the middle of the shaft.

But..hmyeah...I guess I'll try what the look like ingame and then decide...I mean, if you're using layers it might not be much work to do the grip for all three versions, but I do not want to give you unnecessary work.^^

**Comment by Squeekblach** [comment]
I googled modern javelins, yes it is in the middle of the shaft. Also, how long do you think it takes to make textures? xD... It doesn't really take that long for me... I made all the gun textures in like an hour with frequent breaks to check on things.

**Comment by Squeekblach** [comment]
![javelin1wrap](https://cloud.githubusercontent.com/assets/16748858/12435208/0198a6b2-beda-11e5-8293-15145235c3a6.png)
![javelin2wrap](https://cloud.githubusercontent.com/assets/16748858/12435211/04401242-beda-11e5-9691-532b2d17d0fa.png)
![javelin3wrap](https://cloud.githubusercontent.com/assets/16748858/12435212/061caaf8-beda-11e5-9bf5-c37fc5d6ffae.png)
Done.

**Comment by TheOnlySilverClaw** [comment]
Well, I still do not want anyone to waste time on things we throw away, which will be one out of thhose three textures.^^

Anyway...I guess we did not have a final Katana version so far?

**Comment by Squeekblach** [comment]
Uuurhg... I don't even know with the Katana anymore... Honestly, it would probably be better if we just used a 16x16 one... It's impossible to make a good Katana curve  with 32x32...

Here, I drew up a 16x16 one for example purposes... 
![katana16](https://cloud.githubusercontent.com/assets/16748858/12465356/9de949a6-bf9b-11e5-9a5b-e16d2b4d6b0b.png)
I can change it to your liking.

**Comment by TheOnlySilverClaw** [comment]
Well, I still liked most of those better than this not-katana-formed 16*16 thing^^
But I know your struggle...hmmm...I'll go through what you've sent me so far and see what looks the least bad ingame.^^

**Comment by ThexXTURBOXx** [comment]
#74 Could you help us? ^^

**Comment by ThexXTURBOXx** [comment]
Could you try to do a Katana-Texture again? I coded them and I don't wanna steal Balkon's Textures for them...

**Comment by ThexXTURBOXx** [comment]
Ok. Silvercatcher just sent me the other Katana-textures: http://imgur.com/a/XqJN4
If you can: I would like to have the second texture, but not _so_ bent. Could you manage to do this?

**Comment by Squeekblach** [comment]
![k 2lb](https://cloud.githubusercontent.com/assets/16748858/12821428/6df7ede6-cb31-11e5-9037-9fa71c08cb46.png)
Like that?

**Comment by ThexXTURBOXx** [comment]
Yeah, looks nice! Could you do the Wood, Stone etc. textures of it?

**Comment by Squeekblach** [comment]
![woodenkatana](https://cloud.githubusercontent.com/assets/16748858/12824016/1e18d446-cb3d-11e5-8fda-a6abc0a40799.png)
![stonekatana](https://cloud.githubusercontent.com/assets/16748858/12824021/2126edb2-cb3d-11e5-87b8-f03229f83f49.png)
![goldkatana](https://cloud.githubusercontent.com/assets/16748858/12824025/23902212-cb3d-11e5-8c44-eda16d7bd091.png)
![diamondkatana](https://cloud.githubusercontent.com/assets/16748858/12824026/24991c54-cb3d-11e5-9188-af48ef720a85.png)
That should be all of them. I was wondering if there should be a brass variant of the Blunderbuss considering that actual Blunderbuss barrels were made out of either steel or brass.

**Comment by ThexXTURBOXx** [comment]
Thank you!
A brass variant of blunderbuss is a good idea. But I think, that we should add this in the "Integration update", because steel and brass are features of other mods.

**Comment by Squeekblach** [comment]
That's exactly what I meant by it. :P

**Comment by TheOnlySilverClaw** [comment]
Can we get a normal crossbow and a really big one? I have things to break. ;)
I mean, I can do the scaling...it should just look heavy.

**Comment by Squeekblach** [comment]
![crossbow](https://cloud.githubusercontent.com/assets/16748858/12835684/5781a526-cb80-11e5-94a6-76ed01e3387b.png)
![crossbowloaded](https://cloud.githubusercontent.com/assets/16748858/12835687/591bb110-cb80-11e5-9aa4-55e811fddc53.png)
![largecrossbow](https://cloud.githubusercontent.com/assets/16748858/12835688/5ac70af0-cb80-11e5-9b8a-a3caf51383d4.png)
![largecrossbowloaded](https://cloud.githubusercontent.com/assets/16748858/12835690/5c950152-cb80-11e5-8279-d9c646338aa0.png)
![cross-bolt](https://cloud.githubusercontent.com/assets/16748858/12835729/b2b078d2-cb80-11e5-994c-a658cefd5239.png)
Tell me what you think.

**Comment by Squeekblach** [comment]
What sabre texture is that in the latest version?

**Comment by TheOnlySilverClaw** [comment]
About the crossbows: looks good, but I realize I have to find out how to switch between textures when loading.

And whatever is in this folder: https://github.com/TheOnlySilverClaw/Reforged/tree/master/resources/assets/reforged/textures/items is currently in use.
I think that was made by badaspig?

**Comment by ThexXTURBOXx** [comment]
Hi again ^^
I would have a new texture request: I would need a Keris (It would be cool, if its texture is based on [this one](https://s3.amazonaws.com/images.ecwid.com/images/1231108/257138161.jpg)).
P.S.: There is no need to hurry. I just need it until the 0.7-preversions release.

**Comment by Squeekblach** [comment]
Sounds good! This one looks like it's made out of Damascus steel. Would it need to be in all the different materials?

**Comment by ThexXTURBOXx** [comment]
Hmmm... I think it would be enough to have one out of - I think - Iron?
But it would be cool, if it is a little bit darker iron (Good to know, that the one in the picture is made out of Damascus Steel: The Integration Update is getting bigger and bigger ^^). 
I forgot: I would need a simple texture for the "Gold-Rod" (A stick crafted out of 2 Gold ingots, used to craft the Keris). Thank you! ^^

**Comment by Squeekblach** [comment]
Should I make the handle gold colored?

**Comment by ThexXTURBOXx** [comment]
According to the crafting recipe: Yeah, would be a good thought ^^ I would have forget it :D

**Comment by Squeekblach** [comment]
![kerisv1](https://cloud.githubusercontent.com/assets/16748858/13094828/4c3c2470-d4db-11e5-8e09-8ebed49f3733.png)
![kerisgoldhandlev1](https://cloud.githubusercontent.com/assets/16748858/13094830/4ddee286-d4db-11e5-9544-be3a503f6257.png)
![kerisv2](https://cloud.githubusercontent.com/assets/16748858/13094833/4fc26596-d4db-11e5-8d07-25cc9ab7f426.png)
![kerisv2goldhandle](https://cloud.githubusercontent.com/assets/16748858/13094836/51edca9a-d4db-11e5-95ac-50a2bcb3db0f.png)
I made a few test versions cause making curves like that aren't the easiest things, tell me what you think and what I should improve on.

**Comment by TheOnlySilverClaw** [comment]
Errr...I was thinking of making it golden, since that's the most enchantable material in Minecraft. And yes, a good crafting recipe might be tricky to find but I'm not sure if making an extra item for that is the best solution.

**Comment by ThexXTURBOXx** [comment]
@TheOnlySilverClaw But if it's all golden, the crafting recipe (which I want as iron / in the integration update the iron wil be replaced with steel) has to be out of gold...
@SnowballFlame I like the 4th texture ^^ I will add it for now. If the crafting recipe gets changed, I will contact you again and ask for another color :D

**Comment by TheOnlySilverClaw** [comment]
Sooo... I will have my Swedish exam on Tuesday and can hopefully finish the Necromancer's Staff next week. I'm not actually sure how to make it look, though...
Maybe the staff could be made out of obsidian, the tip could be an undead mob's head... depending on how rare the staff should be.
Any suggestions?

**Comment by ThexXTURBOXx** [comment]
And I had my stage play yesterday and 2 days ago. I have more time now again ^^

**Comment by Squeekblach** [comment]
![necromancer sstaff](https://cloud.githubusercontent.com/assets/16748858/13557263/b2e066a8-e3ba-11e5-9158-c3a654b887b1.png)
I tried to make a Necromancer's staff. What do you think?

**Comment by ThexXTURBOXx** [comment]
The idea of the texture is genious!
I don't know, if it looks better then, but I think, if the head is a little bit brighter, it would look better. But I don't know.

**Comment by TheOnlySilverClaw** [comment]
I'm not sure about the mob heads as a tip, but well...if you really want it, maybe make them a separate layer, so we can make it look a little 3-dimensional.

**Comment by TheOnlySilverClaw** [comment]
https://github.com/TheOnlySilverClaw/Reforged---Cross-and-Grave/tree/master/java/org/silvercatcher/reforged_cag
So, I decided to put the crosses and necromancer staffs into a side project, so I can release them as a standalone mod for now.
I came to the conclusion that I could use three different textures for both items. I'm still not sure about the staffs, but the crosses could make do with the following changes:
1. wooden cross with gold centre
2. golden cross with diamond centre
3. diamond cross with emerald centre
And maybe make the centres their own layer, so they can stand out a little.

**Comment by TheOnlySilverClaw** [comment]
So, I ended up doing my own textures for now. I like the crosses a little thinner, but maybe something between our versions would be nice. If you have the time, feel free to give them a final retouch, otherwise we will have to live with these:

![holy_cross_tier1](https://cloud.githubusercontent.com/assets/6529548/13666259/e3318762-e6b0-11e5-8d78-ceec1844db53.png)
![holy_cross_tier2](https://cloud.githubusercontent.com/assets/6529548/13666261/e349949c-e6b0-11e5-9724-8f4e321a948a.png)
![holy_cross_tier3](https://cloud.githubusercontent.com/assets/6529548/13666260/e33a023e-e6b0-11e5-8796-f747d5d99bba.png)

**Comment by ThexXTURBOXx** [comment]
Hi, I would need a texture for a Caltrop.
I thought of something like this: https://upload.wikimedia.org/wikipedia/commons/1/1e/Caltrop.jpg
Is this possible? ^^

**Comment by Squeekblach** [comment]
![caltrop](https://cloud.githubusercontent.com/assets/16748858/13829522/cf9b4836-eb9d-11e5-94eb-f0d1bb602821.png)

**Comment by Squeekblach** [comment]
Whoops, clicked the wrong button just there.

**Comment by ThexXTURBOXx** [comment]
No problem ^^ And thanks for the texture: It fits the entity one's perfectly!
If you have enough time, could you make a texture for dynamite, too?
I don't wanna steal Balkon's one ^^

**Comment by ThexXTURBOXx** [comment]
Hello again,
I would need a Dynamite texture (Right now we use Balkon's one...) ^^
And I am asking, if you could make some more crossbow-textures. I want to animate the crossbow a little bit, while reloading. I took those textures by you for now:
![Crossbow 1](https://cloud.githubusercontent.com/assets/16748858/12835688/5ac70af0-cb80-11e5-9b8a-a3caf51383d4.png)
![Crossbow 2](https://cloud.githubusercontent.com/assets/16748858/12835690/5c950152-cb80-11e5-8279-d9c646338aa0.png)
Is it possible, that you make like 2 or 3 "stages between the 2"?
That would be awesome :)

**Comment by Squeekblach** [comment]
![dynamite](https://cloud.githubusercontent.com/assets/16748858/13972523/e65992e0-f06f-11e5-9b5e-21a32e8b03d5.png)
Sorry it's late, I've been busy lately. I'll do the crossbow textures soon.

**Comment by ThexXTURBOXx** [comment]
No problem and thanks for the Dynamite ^^

**Comment by Squeekblach** [comment]
![largecrossbow](https://cloud.githubusercontent.com/assets/16748858/13999741/0d67f404-f114-11e5-9280-47a688a12883.png)
![largecrossbowpulling1](https://cloud.githubusercontent.com/assets/16748858/13999745/109cae08-f114-11e5-9cc6-9c6afa13aed2.png)
![largecrossbowpulling2](https://cloud.githubusercontent.com/assets/16748858/13999747/1340676c-f114-11e5-9806-3c65cb4facc9.png)
![largecrossbowloaded](https://cloud.githubusercontent.com/assets/16748858/13999754/1793688c-f114-11e5-871c-b3964c7d7787.png)
Use these instead, I noticed some things that were wrong with the old crossbows so I fixed them, I also made two stages in between.

**Comment by ThexXTURBOXx** [comment]
Wow, awesome! Thanks!
I think, that I just found out how I can animate them like I want ^^
1 Request again XD
Could you make the last one without an arrow, too? Then I could let it look like the player would lay it on the crossbow.

**Comment by Squeekblach** [comment]
![largecrossbowunloaded](https://cloud.githubusercontent.com/assets/16748858/14002229/019984b4-f121-11e5-99d8-d0ddcf8c1da7.png)

**Comment by ThexXTURBOXx** [comment]
Nice! That should be everything needed for the crossbow. Thank you!

**Comment by ThexXTURBOXx** [comment]
Hi @SnowballFlame 
I am working again on the mod and I would need some textures for pikes (will be crafted out of all vanilla materials).
Are you able to make those?

**Comment by Squeekblach** [comment]
Yeah, but I'd need to know how you want them to look.
Pikes in real life closely resemble a spear.

**Comment by ThexXTURBOXx** [comment]
Thanks!
The tip should look like this one: http://www.weapons-universe.com/Swords/Polearms.jpg (The one on the very right)
The stick should look like this: http://vignette2.wikia.nocookie.net/thesaoproject/images/0/0d/Pike.jpg/revision/latest?cb=20131210064930

**Comment by Squeekblach** [comment]
![woodenpike](https://cloud.githubusercontent.com/assets/16748858/17041428/fa26a84a-4f73-11e6-88c5-665d80fe9ace.png)
![stonepike](https://cloud.githubusercontent.com/assets/16748858/17041431/fc9cef44-4f73-11e6-94b8-72c90d4f6e7a.png)
![ironpike](https://cloud.githubusercontent.com/assets/16748858/17041436/086d5ff2-4f74-11e6-8c10-98aa81d0437a.png)
![goldpike](https://cloud.githubusercontent.com/assets/16748858/17041444/0c020596-4f74-11e6-8fbb-ec3f0f2e3cf7.png)
![diamondpike](https://cloud.githubusercontent.com/assets/16748858/17041448/0f171ac8-4f74-11e6-8def-13beacbef042.png)
What do you think?

**Comment by ThexXTURBOXx** [comment]
They look perfect, I will include them.
Thanks!

**Comment by ThexXTURBOXx** [comment]
Hi again ^^
Could you make a Mace texture in all 5 materials?
It should look like this:
![Mace](http://cdn.playbuzz.com/cdn/948ffe1c-b5f6-47e5-88dc-a869cf86677e/a01e2425-a395-4ada-8fa6-fa2e76388f9b.jpg)

**Comment by Squeekblach** [comment]
![woodenmace](https://cloud.githubusercontent.com/assets/16748858/17265570/1704945e-55be-11e6-8929-3aa5e4f75671.png)
![stonemace](https://cloud.githubusercontent.com/assets/16748858/17265576/1f3489cc-55be-11e6-950f-db3ce45a70c0.png)
![ironmace](https://cloud.githubusercontent.com/assets/16748858/17265578/2473301e-55be-11e6-8e90-75fac04ff149.png)
![goldmace](https://cloud.githubusercontent.com/assets/16748858/17265582/2a2d1cb8-55be-11e6-9e6d-98766538be02.png)
![diamondmace](https://cloud.githubusercontent.com/assets/16748858/17265585/2cd74236-55be-11e6-8131-c7b9d9f77c6a.png)
Sorry it took so long, the past few days have been busy.
What do you think?

**Comment by ThexXTURBOXx** [comment]
No problem, they look pretty good so far.
Could you make a 32x32-version of them?
Maybe they will be recognized even better then :)

**Comment by Squeekblach** [comment]
Sorry, I'll do it as soon as I can. I've been a little busy lately...

**Comment by ThexXTURBOXx** [comment]
No problem, just take your time. I am very busy at the moment, too

**Comment by Squeekblach** [comment]
![32xwoodmace](https://cloud.githubusercontent.com/assets/16748858/17673928/43f2bfe6-62f1-11e6-8f88-fbe495cfae71.png)
![32xstonemace](https://cloud.githubusercontent.com/assets/16748858/17673931/4580cc4a-62f1-11e6-99db-a86ab99f1b31.png)
![32xironmace](https://cloud.githubusercontent.com/assets/16748858/17673933/4773ff40-62f1-11e6-9558-9a2aa8b3ad07.png)
![32xgoldmace](https://cloud.githubusercontent.com/assets/16748858/17673935/48e8e08e-62f1-11e6-8f84-56b25c72e442.png)
![32xdiamondmace](https://cloud.githubusercontent.com/assets/16748858/17673938/4a7f1170-62f1-11e6-9145-15569bef625a.png)
Finally got to making them. What are your thoughts?

**Comment by ThexXTURBOXx** [comment]
They look good, I will include them, when I'm back from Italy

**Comment by ThexXTURBOXx** [comment]
Misclick, sry

**Comment by ThexXTURBOXx** [comment]
Ok, now I have more time working on Reforged, could you make some textures for Dirks (something like this in all materials: ![Dirk](http://www.sea-thieves.com/education_pages/education_photos/weapons_rn-dirk.gif) )?
That would be great :)

**Comment by Squeekblach** [comment]
![wooden_dirk](https://cloud.githubusercontent.com/assets/16748858/18693809/bffb8940-7f72-11e6-8674-7fb6b3767933.png)
![stone_dirk](https://cloud.githubusercontent.com/assets/16748858/18693815/c47eb0d2-7f72-11e6-8b9f-10d5eb95d4ea.png)
![golden_dirk](https://cloud.githubusercontent.com/assets/16748858/18693818/c8d959de-7f72-11e6-9558-5b2e8cb9f77a.png)
![iron_dirk](https://cloud.githubusercontent.com/assets/16748858/18693823/d3777c2c-7f72-11e6-9877-729899e900fc.png)
![diamond_dirk](https://cloud.githubusercontent.com/assets/16748858/18693824/d8de4088-7f72-11e6-90c2-ac3babb97b33.png)
How are these?

**Comment by ThexXTURBOXx** [comment]
They look good, thanks! :)

**Comment by Squeekblach** [comment]
I've been keeping up silently with the updates recently. Just thought I'd let you know, I'm still here if you need anymore work done.

**Comment by Sunconure11** [comment]
He's on CurseForge, try messaging him there. I tried to show him something that might allow him to fix some of the strangeness with some weapons and what not, but he has not shown up.

You could look at Baykok's bow in Totemic for seeing how to apply any changes to the ranged weaponry, as well. https://github.com/TeamTotemic/Totemic/blob/9ef2837bd6296003bd8b9cf855c8c91b9438fcaa/src/main/resources/assets/totemic/models/item/baykok_bow.json

For handhelds, look at my athame in my own mod I'm building:
https://github.com/Um-Mitternacht/Witchworks/blob/1.11.2/src/main/resources/assets/witchworks/models/item/athame.json

**Comment by ThexXTURBOXx** [comment]
After bug fixing, I will need you, SnowballFlame ;)
 
I've read your comment and thought, I would have replied to it. Strange. Well, I will definetly use that in the next update ;) Thank you!

**Comment by ThexXTURBOXx** [comment]
Okay, I'm here again. Pushed out a new update yesterday. I now want to start working on the 0.8-update.
A Cannon (with a Cannon Ball of course), Flail (Wood - Diamond), Halberd (Wood - Diamond) and Warhammer (Wood - Diamond) is planned.
A popular German YouTuber contacted me in the mean time and wanted to know, when the cannon would be ready. I think, that I might start with the cannon to give him a exclusive pre-release (he needs it for a project with many other popular German YouTubers).
So, I would need textures for all of those. The Cannon will need 4 textures. One for each the Cannon and Cannon Ball item and one for each the Cannon and Cannon Ball entity (which will get pretty complicated to make). I will send you a UV-Texture with all of the sides marked on it, so you can texture it the right way.
Just tell me, when you are ready and thank you in advance ^^

**Comment by Squeekblach** [comment]
Yeah, I've textured models before, shouldn't be too complex.
Anyway, I'm ready, send it when you can.

**Comment by ThexXTURBOXx** [comment]
Perfect, thank you ^^

**Comment by Squeekblach** [comment]
Flails:
![woodflail](https://user-images.githubusercontent.com/16748858/31580672-150445dc-b125-11e7-968d-1fc3dce3a6e5.png)
![stoneflail](https://user-images.githubusercontent.com/16748858/31580673-16dc6466-b125-11e7-92f6-4a02333dfe35.png)
![ironflail](https://user-images.githubusercontent.com/16748858/31580674-18877bf2-b125-11e7-8126-f64f6e93b3ca.png)
![goldflail](https://user-images.githubusercontent.com/16748858/31580675-1a53dbc4-b125-11e7-88ab-fab2c7e22eef.png)
![diamondflail](https://user-images.githubusercontent.com/16748858/31580676-1bb6332c-b125-11e7-8b8d-9fd1265142c2.png)

Halberds:
![woodhalberd](https://user-images.githubusercontent.com/16748858/31580677-299a5c70-b125-11e7-9daa-c7dd7b6aaae3.png)
![stonehalberd](https://user-images.githubusercontent.com/16748858/31580678-2bdcd846-b125-11e7-9d67-879b1ab66126.png)
![ironhalberd](https://user-images.githubusercontent.com/16748858/31580679-2f1be204-b125-11e7-9364-62acb440c181.png)
![goldhalberd](https://user-images.githubusercontent.com/16748858/31580680-34c432ba-b125-11e7-8b02-4b08303f1e96.png)
![diamondhalberd](https://user-images.githubusercontent.com/16748858/31580682-3849cdd2-b125-11e7-9192-7076032d5769.png)

War hammers:
![woodwarhammer](https://user-images.githubusercontent.com/16748858/31580685-50ca8ec8-b125-11e7-90cf-9282db275b12.png)
![stonewarhammer](https://user-images.githubusercontent.com/16748858/31580686-52b27a8e-b125-11e7-84e6-82575f524955.png)
![ironwarhammer](https://user-images.githubusercontent.com/16748858/31580688-541b6228-b125-11e7-9393-2c5b9127eda5.png)
![goldwarhammer](https://user-images.githubusercontent.com/16748858/31580689-5543b006-b125-11e7-9d9b-0d47b4379ede.png)
![diamondwarhammer](https://user-images.githubusercontent.com/16748858/31580691-565b22d0-b125-11e7-9d81-196487d66736.png)

Sorry it took me a month, forgot for a few weeks, then had to find the time.
Tell me what you think.

**Comment by ThexXTURBOXx** [comment]
No problem :) They look great!
The thing with the cannon: Right now I just re-modeled the cannon by BalkondeurAlpha (I looked at his model and then did it myself). But I want to have it look different. I need some time to think about a new model... When I'm finished with that, I will contact you again
